[pool wowflow]
user = wowflow
group = wowflow
listen = /var/run/wowflow.sock
pm = ondemand
pm.max_children = 5
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 2
php_admin_value[memory_limit] = 512M
pm.process_idle_timeout = 10s
