
server {
    server_name natal-karta.ru;
    include /etc/nginx/snippets/block-xmlrpc-global.conf;

    # Block public wp-cron (system cron runs via PHP-CLI)
    location = /wp-cron.php {
        allow 127.0.0.1;
        allow ::1;
        allow 5.101.114.114;
        deny all;
        access_log off;
        log_not_found off;
    }

    listen 212.109.223.109:80;
    listen 212.109.223.109:443 ssl;
    
        

    ssl_certificate "/var/www/httpd-cert/natal-karta.ru_2026-02-27-16-13_53.crt";
    ssl_certificate_key "/var/www/httpd-cert/natal-karta.ru_2026-02-27-16-13_53.key";

    charset utf-8;

    gzip on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/css image/x-ico application/pdf image/jpeg image/png image/gif application/javascript application/x-javascript application/x-pointplus;
    gzip_comp_level 1;
    
    set $root_path /var/www/natal-karta/data/www/natal-karta.ru;
    root $root_path;
    disable_symlinks if_not_owner from=$root_path;

    location / {
        index index.php;
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;fastcgi_pass unix:/var/run/natal-karta.ru.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
     }


    location ~* ^.+\.(jpg|jpeg|gif|png|svg|js|css|mp3|ogg|mpeg|avi|zip|gz|bz2|rar|swf|ico|7z|doc|docx|map|ogg|otf|pdf|ttf|tif|txt|wav|webp|woff|woff2|xls|xlsx|xml)$ {
        try_files $uri $uri/ /index.php?$args;
        expires 1d;
    
    }

    location @fallback {fastcgi_pass unix:/var/run/natal-karta.ru.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
    }

    include "/etc/nginx/fastpanel2-sites/natal-karta/natal-karta.ru.includes";
    include /etc/nginx/fastpanel2-includes/*.conf;

    error_log /var/www/natal-karta/data/logs/natal-karta.ru-frontend.error.log;
    access_log /var/www/natal-karta/data/logs/natal-karta.ru-frontend.access.log;
}
server {
    server_name www.natal-karta.ru  ;
    include /etc/nginx/snippets/block-xmlrpc-global.conf;

    # Block public wp-cron (system cron runs via PHP-CLI)

    listen 212.109.223.109:80;
    listen 212.109.223.109:443 ssl;
    
        

    ssl_certificate "/var/www/httpd-cert/natal-karta.ru_2026-02-27-16-13_53.crt";
    ssl_certificate_key "/var/www/httpd-cert/natal-karta.ru_2026-02-27-16-13_53.key";

    
    return 301 $scheme://natal-karta.ru$request_uri;
    

    error_log /var/www/natal-karta/data/logs/natal-karta.ru-frontend.error.log;
    access_log /var/www/natal-karta/data/logs/natal-karta.ru-frontend.access.log;
}
