server {

    listen xxx.xxx.xxx.222:80 default_server;
    listen xxx.xxx.xxx.222:443 ssl default_server;


    listen [2a0a:4cc0:c0:ef28:589d:cff:fea6:f0a1]:80 default_server;
    listen [2a0a:4cc0:c0:ef28:589d:cff:fea6:f0a1]:443 ssl default_server;

    server_name _;

    ssl_certificate /etc/nginx/ssl-certs/parking.crt;
    ssl_certificate_key /etc/nginx/ssl-certs/parking.key;

    include /etc/nginx/fastpanel2-includes/letsencrypt.conf;

    location / {
        root /var/www;
        try_files /index.html =404;
    }

    access_log /var/log/nginx/parking.access.log;
}
