# SHARED ALIASES FOR ROOT AND ADMINER
alias infooo='[ "$(id -u)" = "0" ] && /opt/server_tools/scripts/infooo.sh || sudo /opt/server_tools/scripts/infooo.sh'
alias sos='sudo /opt/server_tools/scripts/server_audit.sh'
alias sos1='sudo /opt/server_tools/scripts/server_audit.sh 1h'
alias sos3='sudo /opt/server_tools/scripts/server_audit.sh 3h'
alias sos24='sudo /opt/server_tools/scripts/server_audit.sh 24h'
alias sos120='sudo /opt/server_tools/scripts/server_audit.sh 120h'
alias stat='sudo /opt/server_tools/scripts/amnezia_stat.sh'
alias backup='sudo /opt/server_tools/scripts/system_backup.sh'
alias fight='sudo /opt/server_tools/scripts/block_bots.sh'
alias domains='sudo /opt/server_tools/scripts/domains.sh'
alias antivir='cscli decisions list'
alias banlog='cscli alerts list -l 20'
alias load='cd /opt/server_tools && git pull --rebase && echo "Updated from GitHub"'
alias save='cd /opt/server_tools && git add . && git commit -m "Save $(date +%Y-%m-%d_%H:%M)" && git push origin main && echo "Saved to GitHub"'
