# SHARED ALIASES FOR ROOT AND ADMINER
alias infooo='sudo /opt/server_tools/scripts/infooo.sh'
alias sos='sudo /opt/server_tools/scripts/sos.sh'
alias sos1='sudo /opt/server_tools/scripts/sos.sh 1'
alias sos3='sudo /opt/server_tools/scripts/sos.sh 3'
alias sos24='sudo /opt/server_tools/scripts/sos.sh 24'
alias sos120='sudo /opt/server_tools/scripts/sos.sh 120'
alias stat='sudo /opt/server_tools/scripts/stat.sh'
alias backup='sudo /opt/server_tools/scripts/backup.sh'
alias fight='sudo /opt/server_tools/scripts/fight.sh'
alias domains='sudo /opt/server_tools/scripts/domains.sh'
alias antivir='sudo /opt/server_tools/scripts/antivir.sh'
alias banlog='sudo /opt/server_tools/scripts/banlog.sh'
alias load='cd /opt/server_tools && git pull --rebase && echo "Обновлено из GitHub"'
alias save='cd /opt/server_tools && git add . && git commit -m "Save $(date +%Y-%m-%d_%H:%M)" && git push origin main && echo "Сохранено в GitHub"'
