# SHARED ALIASES FOR ROOT AND ADMINER
# Version: v2026-03-19
alias infooo='[ "$(id -u)" = "0" ] && /opt/server_tools/scripts/infooo.sh || sudo /opt/server_tools/scripts/infooo.sh'
alias sos='sudo /opt/server_tools/scripts/server_audit.sh'
alias sos1='sudo /opt/server_tools/scripts/server_audit.sh 1h'
alias sos3='sudo /opt/server_tools/scripts/server_audit.sh 3h'
alias sos24='sudo /opt/server_tools/scripts/server_audit.sh 24h'
alias sos120='sudo /opt/server_tools/scripts/server_audit.sh 120h'
alias backup='sudo /opt/server_tools/scripts/system_backup.sh'
alias fight='sudo /opt/server_tools/scripts/block_bots.sh'
alias domains='sudo /opt/server_tools/scripts/domains.sh'
alias banlog='sudo /opt/server_tools/scripts/banlog.sh'
alias load='cd /opt/server_tools && git pull --rebase && source /opt/server_tools/shared_aliases.sh && echo "Updated from GitHub"'
alias save='cd /opt/server_tools && git add . && git commit -m "Save $(date +%Y-%m-%d_%H:%M)" && git push origin main && echo "Saved to GitHub"'
alias 303='bash /opt/server_tools/scripts/log_303.sh'
alias sta='sudo /opt/server_tools/scripts/amnezia_stat.sh'
alias aw='/opt/server_tools/scripts/amnezia_stat.sh'
alias aws-ping='sudo /opt/server_tools/scripts/aws_ping.sh'
alias awsping='sudo /opt/server_tools/scripts/aws_region_test.sh'
alias cop='sudo /opt/server_tools/scripts/repo_export.sh'
alias crowdsec='sudo /opt/server_tools/scripts/install_crowdsec.sh'

# --- Antivirus ClamAV ---
alias antivir='bash /opt/server_tools/scripts/scan_clamav.sh'
alias antivir-stop='bash /opt/server_tools/scripts/scan_clamav.sh --stop'
alias antivir-status='bash /opt/server_tools/scripts/scan_clamav.sh --status'
