# Ansible Inventory — All Servers
# Version: v2026-03-28
# = Rooted by VladiMIR | AI =

[main]
server-222 ansible_host=xxx.xxx.xxx.222 ansible_user=root
server-109 ansible_host=xxx.xxx.xxx.109 ansible_user=root

[vpn]
vpn-alex-47     ansible_host=xxx.xxx.xxx.47    ansible_user=root
vpn-4ton-237    ansible_host=xxx.xxx.xxx.237  ansible_user=root
vpn-tatra-9     ansible_host=xxx.xxx.xxx.9    ansible_user=root
vpn-shahin-227  ansible_host=xxx.xxx.xxx.227  ansible_user=root
vpn-stolb-24    ansible_host=xxx.xxx.xxx.24   ansible_user=root
vpn-pilik-178   ansible_host=xxx.xxx.xxx.178    ansible_user=root
vpn-ilya-176    ansible_host=xxx.xxx.xxx.176  ansible_user=root
vpn-so-38       ansible_host=xxx.xxx.xxx.38   ansible_user=root

[all_servers:children]
main
vpn

[all_servers:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
